routes/web.php
<?php

use App\Http\Controllers\CategorieController;
use App\Http\Controllers\CommandeController;
use App\Http\Controllers\HomeController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ProduitController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
..
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', [HomeController::class,"index"])->name("index");

Route::post('/add-panier' ,[HomeController::class,"addPanier"])->name("add-panier");
Route::get('/show-panier' ,[HomeController::class,"showPanier"])->name("show-panier");
Route::get('/clear-panier' ,[HomeController::class,"clearPanier"])->name("clear-panier-item");
Route::post('/remove-panier-item' ,[HomeController::class,"removePanier"])->name("remove-panier-item");

Route::get("/categories/search", [CategorieController::class,"search"])->name("categories.search");
Route::get("/produits/search", [ProduitController::class,"search"])->name("produits.search");

Route::resource("categories",CategorieController::class);
Route::resource("produits",ProduitController::class);
Route::resource("commandes",CommandeController::class);

// Route::get('/produits', [ProduitController::class, 'filter'])->name('produits.filter');
// Route::get('/produits/filter', [ProduitController::class, 'index'])->name('produits.index');

app/Models/Commande.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class Commande extends Model
{
    use HasFactory;
    protected $fillable=[
        "id_commande",
        "datetime"

    ];
    public function client(){
        return $this->belongsTo(Client::class);
    }
}

app/Http/Controllers/CommandeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class CommandeController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        //
        return "command index";
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        //
        return view("commandes.create");
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        //

    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, string $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        //
    }
}

resources/views/commandes/create.blade.php
@extends('layouts.admin')
@section('title', 'Create Commande')
@section('content')
    <h1>Creer une nouvelle Client</h1>
    <form action="{{ route('commandes.store') }}" method="POST" enctype="multipart/form-data">
        @csrf
        <div class="input-group-text">
            <label for="designation">nom:</label>
            <input name="designation" class="form-control mt-0 ms-2" type="text"
                aria-label="Checkbox for following text input">
        </div>

        <div class="input-group-text mt-2">
            <label for="description">prenom:</label>
            <input name="prix_u" class="form-control mt-0 ms-2" type="text" value=""
                aria-label="Checkbox for following text input">
        </div>

        <div class="input-group-text mt-2">
            <label for="description">ville:</label>
            <input name="quantite_stock" class="form-control mt-0 ms-2" type="text" value=""
                aria-label="Checkbox for following text input">
        </div>


        <div class="input-group-text mt-2">
            <label for="description">adress:</label>
            <input name="quantite_stock" class="form-control mt-0 ms-2" type="text" value=""
                aria-label="Checkbox for following text input">
        </div>

        <div class="input-group-text mt-2">
            <label for="description">tele:</label>
            <input name="quantite_stock" class="form-control mt-0 ms-2" type="text" value=""
                aria-label="Checkbox for following text input">
        </div>

        <div class="mt-3">
            <input type="submit" value="Ajouter">
        </div>

    </form>
    <div>
        @if ($errors->any())
            <ul>
                @foreach ($errors->all() as $er)
                    <li>{{ $er }}</li>
                @endforeach
            </ul>



        @endif
    </div>
@endsection